baseURL = "https://szyc.dev"
languageCode = "en"
defaultContentLanguage = "en"

title = "Kamil Szyc"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

googleAnalytics = 'G-J16Q3KZY5N'

[params.author]
  name = "Kamil Szyc"
  headline = ".NET Developer"
  image = "photo.jpg"
  links = [
    { linkedin = "https://www.linkedin.com/in/kamil-szyc/" },
    { github = "https://github.com/kamszyc/" },
  ]
