on: push
name: Deploy website to FTP on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
      with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0
          
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.119.0'
        extended: true
    
    - name: Build
      run: hugo --minify
    
    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./public/
        server-dir: ./www/
